
---
title: "School failures on absence and study time"
author: "Samantha Gouveia"
date: "12/28/2023"
output:
 html_document:
 toc: yes
 toc_depth: 4
 toc_float: yes
 fig_width: 6
 fig_caption: yes
 number_sections: yes
 theme: readable
editor_options:
 chunk_output_type: console
---


```{=html}

<style type="text/css">

/* Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML. it is a simple mechanism for adding style (e.g., fonts, colors, spacing) to Web documents. */

h1.title {  /* Title - font specifications of the report title */
  font-size: 24px;
  color: DarkRed;
  text-align: center;
  font-family: "Gill Sans", sans-serif;
}
h4.author { /* Header 4 - font specifications for authors  */
  font-size: 20px;
  font-family: system-ui;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - font specifications for the date  */
  font-size: 18px;
  font-family: system-ui;
  color: DarkBlue;
text-align: center;
}
h1 { /* Header 1 - font specifications for level 1 section title  */
    font-size: 22px;
    font-family: system-ui;
    color: navy;
    text-align: left;
}
h2 { /* Header 2 - font specifications for level 2 section title */
    font-size: 20px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - font specifications of level 3 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - font specifications of level 4 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

body { background-color:white; }

.highlightme { background-color:yellow; }

p { background-color:white; }

</style>
```



```{r setup, include=FALSE}
d <- read.csv("https://raw.githubusercontent.com/sgouveia23/STA321/main/Assign%203/Houses.csv", 
header = TRUE) 
  options(scipen = 2)


  library(knitr)
   library(leaflet)
   library(EnvStats)
   library(MASS)
   library(phytools)
   library(boot)
   library(psych)
   library(car)
   library(dplyr)
   library(kableExtra)


   
# Specifications of outputs of code in code chunks
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = FALSE,
	results = TRUE, 
	digits = 4)
```
# Residual Analysis 

```{r fig.align='center', warning=TRUE}
l = lm(price ~.,  data = d)
summary(fm)

alteredcoef_model <- format(l$coefficients, scientific = FALSE, digits = 2)
```

```{r residual analysis}

par(mfrow = c(2,2))
plot(l)

```

# Press 
```{r}
pr <- d$price
sqq <- d$sq
nn<- length(sqq)

j <- NULL

for(i in 1:nn){
sqq0 <- sqq[-i]
pr0 <- pr[-i]
m <- lm(sqq0 ~ pr0)
j[i] = as.vector(predict(m, newdata = data.frame(sqq0 = sqq[-i])))
}

press = sum((pr-j)^2)
press

```

```{r}
lon <- d$longitude
lat <- d$latitude 

geo.group = (lon >18) & (lat > 51)# define the geo.group variable
# top-right region = TRUE, other region = FALSE
d$geo.group = as.character(geo.group)

fd = d[, -c(1,5,6)]

```

final.data$logAreaPrice = log(final.data$PriceUnitArea)  # 
## the final model
```{r}
log.price <- lm(log(price) ~ floor + rooms + year +  
                 sq  + geo.group, data = fd)
log.price02 <- lm(logAreaPrice ~ HouseAge + NumConvenStores + sale.year +  
                 Dist2MRT.kilo  + geo.group, data = fd)
cmtrx <- summary(log.price)$coef
cmtrx02 <- summary(log.price02)$coef
kable(cmtrx, caption = "Inferential Statistics of Final Model")
```

# Bootstrap case 
```{r}

log.price <- lm(log(price) ~ floor + rooms + year +  
                 sq  + geo.group, data = fd)

B=100
num.p = dim(model.frame(log.price))[2]
smpl.n = dim(model.frame(log.price))[1]
coef.mtrx = matrix(rep(0, B*num.p), ncol = num.p)

for (i in 1:B){
  bootc.id = sample(1:smpl.n, smpl.n, replace = TRUE)

log.price <- lm(log(price) ~ floor + rooms + year +  
                 sq  + geo.group, data = fd[bootc.id])
coef.mtrx[i,] = coef(log.price.btc)  }
```

# Histogram 
















